const FIRST_WIDTH_BREAKPOINT: string = "1220px";
const SECOND_WIDTH_BREAKPOINT: string = "1085px";
const MOBILE_WIDTH_BREAKPOINT: string = "915px";

export {
  FIRST_WIDTH_BREAKPOINT,
  SECOND_WIDTH_BREAKPOINT,
  MOBILE_WIDTH_BREAKPOINT,
};
